### YamlMime:ManagedReference
items:
- uid: OSR_Client.Configuration
  commentId: N:OSR_Client.Configuration
  id: OSR_Client.Configuration
  children:
  - OSR_Client.Configuration.Config
  langs:
  - csharp
  - vb
  name: OSR_Client.Configuration
  nameWithType: OSR_Client.Configuration
  fullName: OSR_Client.Configuration
  type: Namespace
  assemblies:
  - OSR-Client
references:
- uid: OSR_Client.Configuration.Config
  commentId: T:OSR_Client.Configuration.Config
  name: Config
  nameWithType: Config
  fullName: OSR_Client.Configuration.Config
