### YamlMime:ManagedReference
items:
- uid: OSL_Web.Configuration.Overlay.ChampSelect.View4
  commentId: N:OSL_Web.Configuration.Overlay.ChampSelect.View4
  id: OSL_Web.Configuration.Overlay.ChampSelect.View4
  children:
  - OSL_Web.Configuration.Overlay.ChampSelect.View4.Config
  langs:
  - csharp
  - vb
  name: OSL_Web.Configuration.Overlay.ChampSelect.View4
  nameWithType: OSL_Web.Configuration.Overlay.ChampSelect.View4
  fullName: OSL_Web.Configuration.Overlay.ChampSelect.View4
  type: Namespace
  assemblies:
  - OSL-Web
references:
- uid: OSL_Web.Configuration.Overlay.ChampSelect.View4.Config
  commentId: T:OSL_Web.Configuration.Overlay.ChampSelect.View4.Config
  name: Config
  nameWithType: Config
  fullName: OSL_Web.Configuration.Overlay.ChampSelect.View4.Config
