### YamlMime:ManagedReference
items:
- uid: OSL_Web.Configuration.Overlay.InGame.View1_1
  commentId: N:OSL_Web.Configuration.Overlay.InGame.View1_1
  id: OSL_Web.Configuration.Overlay.InGame.View1_1
  children:
  - OSL_Web.Configuration.Overlay.InGame.View1_1.Config
  langs:
  - csharp
  - vb
  name: OSL_Web.Configuration.Overlay.InGame.View1_1
  nameWithType: OSL_Web.Configuration.Overlay.InGame.View1_1
  fullName: OSL_Web.Configuration.Overlay.InGame.View1_1
  type: Namespace
  assemblies:
  - OSL-Web
references:
- uid: OSL_Web.Configuration.Overlay.InGame.View1_1.Config
  commentId: T:OSL_Web.Configuration.Overlay.InGame.View1_1.Config
  name: Config
  nameWithType: Config
  fullName: OSL_Web.Configuration.Overlay.InGame.View1_1.Config
