### YamlMime:ManagedReference
items:
- uid: OSL_Server.Configuration.Config
  commentId: T:OSL_Server.Configuration.Config
  id: Config
  parent: OSL_Server.Configuration
  children:
  - OSL_Server.Configuration.Config.LoadConfig
  - OSL_Server.Configuration.Config.LoadConfigCDragon
  - OSL_Server.Configuration.Config.LoadConfigChampSelectView1
  - OSL_Server.Configuration.Config.LoadConfigChampSelectView2
  - OSL_Server.Configuration.Config.LoadConfigChampSelectView3
  - OSL_Server.Configuration.Config.LoadConfigServerSocket
  langs:
  - csharp
  - vb
  name: Config
  nameWithType: Config
  fullName: OSL_Server.Configuration.Config
  type: Class
  source:
    remote:
      path: OSL-Server/Configuration/Config.cs
      branch: ChampSelect
      repo: https://github.com/Sky-CSC/OSL.git
    id: Config
    path: ../OSL-Server/Configuration/Config.cs
    startLine: 14
  assemblies:
  - OSL-Server
  namespace: OSL_Server.Configuration
  syntax:
    content: public class Config
    content.vb: Public Class Config
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: OSL_Server.Configuration.Config.LoadConfig
  commentId: M:OSL_Server.Configuration.Config.LoadConfig
  id: LoadConfig
  parent: OSL_Server.Configuration.Config
  langs:
  - csharp
  - vb
  name: LoadConfig()
  nameWithType: Config.LoadConfig()
  fullName: OSL_Server.Configuration.Config.LoadConfig()
  type: Method
  source:
    remote:
      path: OSL-Server/Configuration/Config.cs
      branch: ChampSelect
      repo: https://github.com/Sky-CSC/OSL.git
    id: LoadConfig
    path: ../OSL-Server/Configuration/Config.cs
    startLine: 18
  assemblies:
  - OSL-Server
  namespace: OSL_Server.Configuration
  syntax:
    content: public static void LoadConfig()
    content.vb: Public Shared Sub LoadConfig
  overload: OSL_Server.Configuration.Config.LoadConfig*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
- uid: OSL_Server.Configuration.Config.LoadConfigServerSocket
  commentId: M:OSL_Server.Configuration.Config.LoadConfigServerSocket
  id: LoadConfigServerSocket
  parent: OSL_Server.Configuration.Config
  langs:
  - csharp
  - vb
  name: LoadConfigServerSocket()
  nameWithType: Config.LoadConfigServerSocket()
  fullName: OSL_Server.Configuration.Config.LoadConfigServerSocket()
  type: Method
  source:
    remote:
      path: OSL-Server/Configuration/Config.cs
      branch: ChampSelect
      repo: https://github.com/Sky-CSC/OSL.git
    id: LoadConfigServerSocket
    path: ../OSL-Server/Configuration/Config.cs
    startLine: 27
  assemblies:
  - OSL-Server
  namespace: OSL_Server.Configuration
  syntax:
    content: public static void LoadConfigServerSocket()
    content.vb: Public Shared Sub LoadConfigServerSocket
  overload: OSL_Server.Configuration.Config.LoadConfigServerSocket*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
- uid: OSL_Server.Configuration.Config.LoadConfigCDragon
  commentId: M:OSL_Server.Configuration.Config.LoadConfigCDragon
  id: LoadConfigCDragon
  parent: OSL_Server.Configuration.Config
  langs:
  - csharp
  - vb
  name: LoadConfigCDragon()
  nameWithType: Config.LoadConfigCDragon()
  fullName: OSL_Server.Configuration.Config.LoadConfigCDragon()
  type: Method
  source:
    remote:
      path: OSL-Server/Configuration/Config.cs
      branch: ChampSelect
      repo: https://github.com/Sky-CSC/OSL.git
    id: LoadConfigCDragon
    path: ../OSL-Server/Configuration/Config.cs
    startLine: 42
  assemblies:
  - OSL-Server
  namespace: OSL_Server.Configuration
  syntax:
    content: public static void LoadConfigCDragon()
    content.vb: Public Shared Sub LoadConfigCDragon
  overload: OSL_Server.Configuration.Config.LoadConfigCDragon*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
- uid: OSL_Server.Configuration.Config.LoadConfigChampSelectView1
  commentId: M:OSL_Server.Configuration.Config.LoadConfigChampSelectView1
  id: LoadConfigChampSelectView1
  parent: OSL_Server.Configuration.Config
  langs:
  - csharp
  - vb
  name: LoadConfigChampSelectView1()
  nameWithType: Config.LoadConfigChampSelectView1()
  fullName: OSL_Server.Configuration.Config.LoadConfigChampSelectView1()
  type: Method
  source:
    remote:
      path: OSL-Server/Configuration/Config.cs
      branch: ChampSelect
      repo: https://github.com/Sky-CSC/OSL.git
    id: LoadConfigChampSelectView1
    path: ../OSL-Server/Configuration/Config.cs
    startLine: 169
  assemblies:
  - OSL-Server
  namespace: OSL_Server.Configuration
  syntax:
    content: public static void LoadConfigChampSelectView1()
    content.vb: Public Shared Sub LoadConfigChampSelectView1
  overload: OSL_Server.Configuration.Config.LoadConfigChampSelectView1*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
- uid: OSL_Server.Configuration.Config.LoadConfigChampSelectView2
  commentId: M:OSL_Server.Configuration.Config.LoadConfigChampSelectView2
  id: LoadConfigChampSelectView2
  parent: OSL_Server.Configuration.Config
  langs:
  - csharp
  - vb
  name: LoadConfigChampSelectView2()
  nameWithType: Config.LoadConfigChampSelectView2()
  fullName: OSL_Server.Configuration.Config.LoadConfigChampSelectView2()
  type: Method
  source:
    remote:
      path: OSL-Server/Configuration/Config.cs
      branch: ChampSelect
      repo: https://github.com/Sky-CSC/OSL.git
    id: LoadConfigChampSelectView2
    path: ../OSL-Server/Configuration/Config.cs
    startLine: 185
  assemblies:
  - OSL-Server
  namespace: OSL_Server.Configuration
  syntax:
    content: public static void LoadConfigChampSelectView2()
    content.vb: Public Shared Sub LoadConfigChampSelectView2
  overload: OSL_Server.Configuration.Config.LoadConfigChampSelectView2*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
- uid: OSL_Server.Configuration.Config.LoadConfigChampSelectView3
  commentId: M:OSL_Server.Configuration.Config.LoadConfigChampSelectView3
  id: LoadConfigChampSelectView3
  parent: OSL_Server.Configuration.Config
  langs:
  - csharp
  - vb
  name: LoadConfigChampSelectView3()
  nameWithType: Config.LoadConfigChampSelectView3()
  fullName: OSL_Server.Configuration.Config.LoadConfigChampSelectView3()
  type: Method
  source:
    remote:
      path: OSL-Server/Configuration/Config.cs
      branch: ChampSelect
      repo: https://github.com/Sky-CSC/OSL.git
    id: LoadConfigChampSelectView3
    path: ../OSL-Server/Configuration/Config.cs
    startLine: 204
  assemblies:
  - OSL-Server
  namespace: OSL_Server.Configuration
  syntax:
    content: public static void LoadConfigChampSelectView3()
    content.vb: Public Shared Sub LoadConfigChampSelectView3
  overload: OSL_Server.Configuration.Config.LoadConfigChampSelectView3*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
references:
- uid: OSL_Server.Configuration
  commentId: N:OSL_Server.Configuration
  name: OSL_Server.Configuration
  nameWithType: OSL_Server.Configuration
  fullName: OSL_Server.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: OSL_Server.Configuration.Config.LoadConfig*
  commentId: Overload:OSL_Server.Configuration.Config.LoadConfig
  name: LoadConfig
  nameWithType: Config.LoadConfig
  fullName: OSL_Server.Configuration.Config.LoadConfig
- uid: OSL_Server.Configuration.Config.LoadConfigServerSocket*
  commentId: Overload:OSL_Server.Configuration.Config.LoadConfigServerSocket
  name: LoadConfigServerSocket
  nameWithType: Config.LoadConfigServerSocket
  fullName: OSL_Server.Configuration.Config.LoadConfigServerSocket
- uid: OSL_Server.Configuration.Config.LoadConfigCDragon*
  commentId: Overload:OSL_Server.Configuration.Config.LoadConfigCDragon
  name: LoadConfigCDragon
  nameWithType: Config.LoadConfigCDragon
  fullName: OSL_Server.Configuration.Config.LoadConfigCDragon
- uid: OSL_Server.Configuration.Config.LoadConfigChampSelectView1*
  commentId: Overload:OSL_Server.Configuration.Config.LoadConfigChampSelectView1
  name: LoadConfigChampSelectView1
  nameWithType: Config.LoadConfigChampSelectView1
  fullName: OSL_Server.Configuration.Config.LoadConfigChampSelectView1
- uid: OSL_Server.Configuration.Config.LoadConfigChampSelectView2*
  commentId: Overload:OSL_Server.Configuration.Config.LoadConfigChampSelectView2
  name: LoadConfigChampSelectView2
  nameWithType: Config.LoadConfigChampSelectView2
  fullName: OSL_Server.Configuration.Config.LoadConfigChampSelectView2
- uid: OSL_Server.Configuration.Config.LoadConfigChampSelectView3*
  commentId: Overload:OSL_Server.Configuration.Config.LoadConfigChampSelectView3
  name: LoadConfigChampSelectView3
  nameWithType: Config.LoadConfigChampSelectView3
  fullName: OSL_Server.Configuration.Config.LoadConfigChampSelectView3
