### YamlMime:ManagedReference
items:
- uid: OSR_Server.Configuration
  commentId: N:OSR_Server.Configuration
  id: OSR_Server.Configuration
  children:
  - OSR_Server.Configuration.Config
  langs:
  - csharp
  - vb
  name: OSR_Server.Configuration
  nameWithType: OSR_Server.Configuration
  fullName: OSR_Server.Configuration
  type: Namespace
  assemblies:
  - OSR-Server
references:
- uid: OSR_Server.Configuration.Config
  commentId: T:OSR_Server.Configuration.Config
  name: Config
  nameWithType: Config
  fullName: OSR_Server.Configuration.Config
